"""
Django settings for qa_figma_testing_main project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", cast=bool)

ALLOWED_HOSTS = []

if DEBUG:
    ALLOWED_HOSTS += ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # external apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.figma',

    # my apps
    'figma_auth',
    'qa',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

     # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",

]

# Provider specific settings
# Figma provider config comes from the SocialApp model (admin), not this dict.
SOCIALACCOUNT_PROVIDERS = {
    'figma': {
        'SCOPE': ['file_content:read', 'projects:read', 'current_user:read'],
    }
}

# Store OAuth access tokens in the DB so FigmaClient can read them later.
# allauth defaults this to False, which means SocialAccount is created but
# SocialToken is never persisted — causing 401 "No Figma token found".
SOCIALACCOUNT_STORE_TOKENS = True

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'qa_figma_testing_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # `allauth` needs this from django
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'qa_figma_testing_main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# source(s) for python manage.py collectstatic
STATICFILES_DIRS = [
        BASE_DIR / "static"
    ]

STATIC_ROOT = BASE_DIR / "staticfiles"  # for production

# Media files (uploaded images: figma PNGs, screenshots, diffs)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Caching (LocMemCache — appropriate for single-user, synchronous, SQLite-only v2)
# https://docs.djangoproject.com/en/6.0/topics/cache/
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'figma-qa-default',
    }
}

# How long to cache Figma API file-tree responses (seconds). Tunable via .env.
FIGMA_FILE_TREE_CACHE_TIMEOUT = config("FIGMA_FILE_TREE_CACHE_TIMEOUT", default=300, cast=int)

# How long to cache Figma frame-image PNG bytes (seconds). Tunable via .env.
FIGMA_FRAME_IMAGE_CACHE_TIMEOUT = config("FIGMA_FRAME_IMAGE_CACHE_TIMEOUT", default=600, cast=int)

# Site ID (required by django-allauth to match SocialApp to current site)
SITE_ID = 1

# allauth: skip email verification for social logins (single-user dev tool)
ACCOUNT_EMAIL_VERIFICATION = "none"

# Login redirect
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'