# Generated by Django 6.0.6 on 2026-06-29 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=255)),
                ('node_id', models.CharField(max_length=255)),
                ('frame_name', models.CharField(max_length=255)),
                ('frame_width', models.IntegerField()),
                ('frame_height', models.IntegerField()),
                ('site_url', models.URLField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('figma_image', models.ImageField(blank=True, null=True, upload_to='figma/')),
                ('site_screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('diff_image', models.ImageField(blank=True, null=True, upload_to='diffs/')),
                ('mismatch_percentage', models.FloatField(blank=True, null=True)),
                ('mismatch_pixels', models.IntegerField(blank=True, null=True)),
                ('threshold', models.FloatField(default=0.1)),
                ('pass_fail', models.CharField(blank=True, max_length=10, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
